import { TestPrice, Patient, Report } from './types';

export const HEALTH_TESTS: TestPrice[] = [
    { id: 'T001', name: 'Red Blood Cell Count (RBC)', price: 100, normalRange: '4-5 Millions/cmm' },
    { id: 'T002', name: 'White Blood Cell Count (WBC)', price: 100, normalRange: '5000-11000/CMM' },
    { id: 'T003', name: 'Platelets', price: 200, normalRange: '150,000-300,000/CMM' },
    { id: 'T004', name: 'Erythrocyte Sedimentation Rate (ESR)', price: 200, normalRange: 'M: 3-12mm/hr, F: 4-15mm/hr' },
    { id: 'T005', name: 'Bleeding Time', price: 100, normalRange: '1-3 minutes' },
    { id: 'T006', name: 'Clotting Time', price: 100, normalRange: '2-6 minutes' },
    { id: 'T007', name: 'Typhoid Test (IGG/IGM)', price: 350, normalRange: 'Negative' },
    { id: 'T008', name: 'Mantoux Test', price: 200, normalRange: '5tu - 10tu' },
    { id: 'T009', name: 'Hemoglobin', price: 100, normalRange: '14.5GM/100ML' },
    { id: 'T010', name: 'Blood Group (A.B.O)', price: 50, normalRange: 'N/A' },
    { id: 'T011', name: 'VDRL', price: 200, normalRange: 'Negative' },
    { id: 'T012', name: 'HIV-1 & HIV-2', price: 300, normalRange: 'Negative' },
    { id: 'T013', name: 'HBsAg (Australia Antigen)', price: 250, normalRange: 'Negative' },
    { id: 'T014', name: 'Hepatitis C Virus (HCV)', price: 350, normalRange: 'Negative' },
    { id: 'T015', name: 'C-Reactive Protein (CRP)', price: 400, normalRange: '0.0-6.0 Mg/L' },
    { id: 'T016', name: 'Rheumatoid Arthritis Factor (RA)', price: 250, normalRange: 'Negative' },
    { id: 'T017', name: 'ASO Titre', price: 350, normalRange: 'Negative < 200iu ml' },
    { id: 'T018', name: 'Uric Acid', price: 200, normalRange: 'M: 2.5-7.0mg/ml, F: 1.5-6.0 mg/ml' },
    { id: 'T019', name: 'BUN', price: 200, normalRange: '7-20 mg/dL' },
    { id: 'T020', name: 'Alkaline Phosphatase', price: 200, normalRange: '30-150 iu/l' },
    { id: 'T021', name: 'Dengue Test', price: 1200, normalRange: 'Negative' },
    { id: 'T022', name: 'Widal Test', price: 200, normalRange: 'Negative' },
    { id: 'T023', name: 'Serum Potassium', price: 200, normalRange: '3.50-5.50 mEq/L' },
    { id: 'T024', name: 'Serum Sodium', price: 200, normalRange: '135.00-145.00 mEq/L' },
    { id: 'T025', name: 'Serum Chloride', price: 200, normalRange: '96.00-106 mEq/L' },
    { id: 'T026', name: 'Serum Calcium', price: 300, normalRange: '9-11 mg/dL' },
    { id: 'T027', name: 'Serum Amylase', price: 450, normalRange: '25-125 U/L' },
    { id: 'T028', name: 'Malarial Parasite (MP)', price: 250, normalRange: 'Negative' },
    { id: 'T029', name: 'Microfilaria (MF)', price: 700, normalRange: 'Negative' },
    { id: 'T030', name: 'Blood Sugar (Random)', price: 50, normalRange: '70-140 mg/dL' },
    { id: 'T031', name: 'Blood Sugar (Fasting)', price: 50, normalRange: '60-100 mg/dL' },
    { id: 'T032', name: 'Blood Sugar (Post Prandial)', price: 50, normalRange: '60-140 mg/dL' },
    { id: 'T033', name: 'Blood Urea', price: 200, normalRange: '11-40 mg' },
    { id: 'T034', name: 'Serum Creatinine', price: 200, normalRange: 'M: 0.7-1.3 mg/dL, F: 0.6-1.1 mg/dL' },
    { id: 'T035', name: 'Bilirubin', price: 200, normalRange: '0.1-1.2 mg/dL' },
    { id: 'T036', name: 'SGPT (ALT)', price: 200, normalRange: '0-40 unit/ml' },
    { id: 'T037', name: 'SGOT (AST)', price: 200, normalRange: '0-35 unit/ml' },
    { id: 'T038', name: 'HCG', price: 100, normalRange: 'Negative' },
    { id: 'T039', name: 'Albumin', price: 200, normalRange: '3.5-5.0 gm/dl' },
    { id: 'T040', name: 'Direct/Indirect Coombs Test', price: 900, normalRange: 'Negative' },
    { id: 'T041', name: 'Troponin-T', price: 1200, normalRange: 'Negative' },
    { id: 'T042', name: 'Cholesterol', price: 200, normalRange: '< 200 mg/dL' },
    { id: 'T043', name: 'Serum Lipase', price: 650, normalRange: '10-140 U/L' },
    { id: 'T044', name: 'Complete Blood Count (CBC)', price: 400, normalRange: 'Varies by parameter' },
    { id: 'T045', name: 'Thyroid Profile (T3, T4, TSH)', price: 600, normalRange: 'Varies by hormone' },
    { id: 'T046', name: 'AMH', price: 1800, normalRange: 'Varies by age/gender' },
    { id: 'T047', name: 'Luteinizing Hormone (LH)', price: 600, normalRange: 'Varies' },
    { id: 'T048', name: 'Follicle-Stimulating Hormone (FSH)', price: 600, normalRange: 'Varies' },
    { id: 'T049', name: 'Electrolytes', price: 600, normalRange: 'Varies' },
    { id: 'T050', name: 'TSH (Standalone)', price: 300, normalRange: '0.4-4.0 mIU/L' },
    { id: 'T051', name: 'Lipid Profile', price: 700, normalRange: 'Varies by component' },
    { id: 'T052', name: 'Prolactin (PRL)', price: 600, normalRange: 'Varies' },
    { id: 'T053', name: 'Semen Analysis', price: 300, normalRange: 'Varies' },
    { id: 'T054', name: 'Biopsy', price: 1200, normalRange: 'N/A' },
    { id: 'T055', name: 'TB Gold Test', price: 2500, normalRange: 'Negative' },
    { id: 'T056', name: 'PT/INR', price: 700, normalRange: '0.8-1.2' },
    { id: 'T057', name: 'HbA1c', price: 700, normalRange: '< 5.7%' },
    { id: 'T058', name: 'Vitamin D (25-OH)', price: 1500, normalRange: '30-100 ng/mL' },
    { id: 'T059', name: 'Anti-CCP', price: 2000, normalRange: '< 20.0 U' },
    { id: 'T060', name: 'ANA Test', price: 5500, normalRange: 'Negative' },
    { id: 'T061', name: 'Beta-HCG (β-HCG)', price: 1000, normalRange: '< 5 mIU/mL' },
];

export const MOCK_PATIENTS: Patient[] = [
    { id: 'P001', name: 'John Doe', age: 45, gender: 'Male', contact: '9876543210' },
    { id: 'P002', name: 'Jane Smith', age: 32, gender: 'Female', contact: '8765432109' },
    { id: 'P003', name: 'Peter Jones', age: 62, gender: 'Male', contact: '7654321098' },
];

export const MOCK_REPORTS: Report[] = [
    {
        id: 'R001',
        patientId: 'P001',
        patientName: 'John Doe',
        patientAge: 45,
        patientGender: 'Male',
        refByDr: 'Dr. Self',
        date: new Date(Date.now() - 2 * 24 * 60 * 60 * 1000).toISOString().split('T')[0],
        tests: [
            { testName: 'Complete Blood Count (CBC)', result: 'Within Normal Limits', normalRange: 'Varies by parameter', price: 400 },
            { testName: 'Blood Sugar (Fasting)', result: '95 mg/dL', normalRange: '60-100 mg/dL', price: 50 },
        ],
    },
    {
        id: 'R002',
        patientId: 'P002',
        patientName: 'Jane Smith',
        patientAge: 32,
        patientGender: 'Female',
        refByDr: 'Dr. House',
        date: new Date(Date.now() - 5 * 24 * 60 * 60 * 1000).toISOString().split('T')[0],
        tests: [
            { testName: 'Thyroid Profile (T3, T4, TSH)', result: 'TSH: 2.1 mIU/L', normalRange: 'Varies by hormone', price: 600 },
            { testName: 'Vitamin D (25-OH)', result: '25 ng/mL', normalRange: '30-100 ng/mL', price: 1500 },
        ],
    }
];